import type { RankedTheme } from '@/lib/types';

const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID;

export async function sendTelegramNotification(
  rankedThemes: RankedTheme[],
  creatorId: number
): Promise<{ success: boolean; error?: string }> {
  'use step';

  if (!TELEGRAM_BOT_TOKEN || !TELEGRAM_CHAT_ID) {
    console.log('[sendTelegramNotification] Missing TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID');
    return { success: false, error: 'Missing Telegram configuration' };
  }

  const top3 = rankedThemes.slice(0, 3);
  
  // Build a nicely formatted message
  const message = formatTelegramMessage(top3, creatorId);

  try {
    const response = await fetch(
      `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: TELEGRAM_CHAT_ID,
          text: message,
          parse_mode: 'HTML',
          disable_web_page_preview: true,
        }),
      }
    );

    if (!response.ok) {
      const errorData = await response.text();
      console.log(`[sendTelegramNotification] Telegram API error: ${errorData}`);
      return { success: false, error: errorData };
    }

    console.log(`[sendTelegramNotification] Sent notification to chat ${TELEGRAM_CHAT_ID}`);
    return { success: true };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.log(`[sendTelegramNotification] Error: ${errorMessage}`);
    return { success: false, error: errorMessage };
  }
}

function formatTelegramMessage(themes: RankedTheme[], creatorId: number): string {
  const header = `<b>Trending in Your Sphere</b>\n<i>Creator: ${creatorId}</i>\n\n`;
  
  const themesList = themes
    .map((theme, index) => {
      const medal = index === 0 ? '🥇' : index === 1 ? '🥈' : '🥉';
      return `${medal} <b>${theme.name}</b>\nScore: ${theme.relevanceScore}/100\n${theme.whyItMatters}\n`;
    })
    .join('\n');

  const footer = `\n<i>Generated by Robota</i>`;

  return header + themesList + footer;
}
